Se agrega Footer y corrigen comentarios anteriores
karmina-jc/Karmina-portfolio pull request #3
Opened 2020-04-08 14:46 UTC by karmina-jc

Descripción 📋
se agregan footer y arreglan detalles de decorado hexagonal en card formato B, se corrigen elementos señalados en comentarios.

Buenas practicas ⚠️#
Coloca una X en aquellas opciones que apliquen

( ) Eslint
(X) Eliminado código muerto
( ) Funciona UI (aun no se agregan href definitivos)

Observaciones 📝
Quedan algunos comentarios pendientes de los pull request anteriores en lo que no me quedaron muy claras las correcciones, por si le puedes dar una mirada o bien te los envío por otro medio.

2020-04-09 13:41 UTC, oscarzambrano116 requested changes
Se tiene que usar un componente reusable para las cards de los proyectos, que por medio de propiedades este se renderice.

2020-04-09 13:41 UTC, oscarzambrano116 commented on src/components/Proyects.jsx
>              <CardProjectB
Esto deberia ser un componente reusable

2020-04-09 13:41 UTC, oscarzambrano116 commented on src/components/footer.jsx
> +                © 2020 Karmina Jara Crespo Developer
Tener el año dinamico con una funcion javascript

2020-04-09 13:41 UTC, oscarzambrano116 commented on src/components/Proyects.jsx
>              <CardProjectB
ejemplo todos deberia usar CardProjectA pero lo renombrabria solo a CardProject

2020-04-17 13:19 UTC, merged

2020-04-17 13:32 UTC, karmina-jc commented on src/components/footer.jsx
> +                © 2020 Karmina Jara Crespo Developer
que buena idea!, si me queda tiempo le hago la función, sino para la siguiente iteración del portafolio.